package com.novasolutions.ipospu.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

// I handle all SQL for the commercial_applications table here.
// I also own the transactional member+application insert because both rows must
// succeed or fail together — splitting them across two DAOs would make it
// impossible to roll back cleanly.
public class CommercialApplicationDAO {

    // I check whether a PENDING application already exists for this email.
    // I only block on PENDING so that a previously rejected applicant can reapply.
    public boolean pendingApplicationExistsForEmail(String email) {
        String sql = "SELECT 1 FROM commercial_applications WHERE email = ? AND status = 'PENDING'";

        try (Connection connection = DatabaseConnection.getInstance().getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setString(1, email);

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                return resultSet.next();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    // I insert a PENDING COMMERCIAL member row and a linked commercial_applications row
    // in a single transaction. If either insert fails I roll back so we never end up
    // with a dangling pending member that has no application record.
    //
    // placeholderPasswordHash is a BCrypt hash of a random UUID generated by the service.
    // It is technically valid BCrypt but nobody knows the plaintext, so the account
    // cannot be logged into until an SA sets a real password on approval.
    public boolean submitApplication(String applicantName, String companyName,
                                     String placeholderPasswordHash,
                                     String companiesHouseNumber, String directorNames,
                                     String businessType, String businessAddress,
                                     String email) {

        String insertMember =
                "INSERT INTO members (full_name, email, password_hash, member_type, membership_status, company_name, created_at) " +
                "VALUES (?, ?, ?, 'COMMERCIAL', 'PENDING', ?, NOW(6))";

        String insertApplication =
                "INSERT INTO commercial_applications (member_id, companies_house_number, director_names, business_type, business_address, email, submitted_at) " +
                "VALUES (?, ?, ?, ?, ?, ?, NOW(6))";

        Connection connection = null;
        try {
            connection = DatabaseConnection.getInstance().getConnection();
            connection.setAutoCommit(false);

            // I insert the pending member first so I can capture the generated ID for the FK.
            long memberId;
            try (PreparedStatement ps = connection.prepareStatement(insertMember, Statement.RETURN_GENERATED_KEYS)) {
                ps.setString(1, applicantName);
                ps.setString(2, email);
                ps.setString(3, placeholderPasswordHash);
                ps.setString(4, companyName);
                ps.executeUpdate();

                try (ResultSet keys = ps.getGeneratedKeys()) {
                    if (keys.next()) {
                        memberId = keys.getLong(1);
                    } else {
                        throw new SQLException("Failed to retrieve generated member ID");
                    }
                }
            }

            // I then insert the application, linking it to the pending member.
            try (PreparedStatement ps = connection.prepareStatement(insertApplication)) {
                ps.setLong(1, memberId);
                ps.setString(2, companiesHouseNumber);
                ps.setString(3, directorNames);
                ps.setString(4, businessType);
                ps.setString(5, businessAddress);
                ps.setString(6, email);
                ps.executeUpdate();
            }

            connection.commit();
            System.out.println("Commercial application submitted for: " + email + " (member_id=" + memberId + ")");
            return true;

        } catch (Exception e) {
            // I roll back on any failure so neither row is left behind.
            if (connection != null) {
                try {
                    connection.rollback();
                    System.out.println("❌ Transaction rolled back for commercial application: " + email);
                } catch (SQLException rollbackEx) {
                    rollbackEx.printStackTrace();
                }
            }
            e.printStackTrace();
            return false;

        } finally {
            if (connection != null) {
                try {
                    connection.setAutoCommit(true);
                    connection.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
